name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    uses: ViniciusOtoni/databricks-local-ci/.github/workflows/databricks-ci.yml@master
    with:
      dbr_version: "15.4-LTS"
      package_dir: "."

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    uses: ViniciusOtoni/databricks-local-ci/.github/workflows/databricks-cd.yml@master
    with:
      package_dir: "."
      bundle_target: "dev"
      auth_method: "pat"
    secrets:
      databricks_host: ${{ secrets.DATABRICKS_HOST }}
      databricks_token: ${{ secrets.DATABRICKS_TOKEN }}
